version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    tty: true
    networks:
      - lanchonete-network
    environment:
      POSTGRES_DB: lanchonete
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    #ports:
    #  - "5435:5432"
    #volumes:
    #  - ./db/data :/postgresql/data

  lanchonete:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - lanchonete-network

networks:
  lanchonete-network:
    driver: bridge