apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lanchonete
  template:
    metadata:
      labels:
        app: lanchonete
    spec:
      containers:
      - name: lanchonete
        image: lucasrfigueiredo/techchallenge-fiap:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:password@postgres-service:5432/lanchonete"
---
apiVersion: v1
kind: Service
metadata:
  name: lanchonete-service
spec:
  selector:
    app: lanchonete
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer 