apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lanchonete
  template:
    metadata:
      labels:
        app: lanchonete
    spec:
      containers:
      - name: lanchonete
        image: lucasrfigueiredo/techchallenge-fiap:latest
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 240
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 240
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 240
          failureThreshold: 30
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: lanchonete-service
spec:
  selector:
    app: lanchonete
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
      nodePort: 31808
  type: NodePort # type of the service. LoadBalancer indicates that our service will be external.

---

apiVersion: v1
kind: Service
metadata:
  name: lanchonete-database-service
spec:
  selector:
    app: lanchonete
  ports:
    - port: 5432

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lanchonete-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lanchonete
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60


  